[profile.default]
solc = "0.8.16"
src = 'src'
out = 'out'
libs = ['lib']

[fmt]
tab_width = 2
number_underscore = 'thousands'
ignore = ['src/HolyPaladinDistributor.sol', 'src/Redeemer.sol']

[rpc_endpoints]
mainnet = 'https://rpc.ankr.com/eth'
ethereum_alchemy = '${ALCHEMY}'