[profile.default]
solc = "0.8.16"
src = 'src'
out = 'out'
libs = ['lib']
optimizer = false 

[fmt]
tab_width = 2
number_underscore = 'thousands'

[rpc_endpoints]
mainnet = 'https://rpc.ankr.com/eth'
ethereum_alchemy = '${ALCHEMY}'
